all:
	wget http://research.microsoft.com/en-us/um/beijing/projects/mslr/data/MSLR-WEB10K.zip
	wget http://research.microsoft.com/en-us/um/beijing/projects/mslr/data/MSLR-WEB30K.zip
	unzip MSLR-WEB10K.zip
	unzip MSLR-WEB30K.zip

